require 'ecdsa_ruby'

success = 0
failure = 0

def assertEqual(a, b)
    if a != b
        failure += 1
        puts "\t\tfail"
    else
        success += 1
        puts "\t\tsuccess"
    end
end

def header(text)
    puts "\n\n#{text} test:"
end

def subHeader(text)
    puts "\t#{text}:"
end


puts "\n\nRunning ECDSA-Ruby tests:"

header("ECDSA")

subHeader("testVerifyRightMessage")
privateKey = EcdsaRuby::PrivateKey.new()
publicKey = privateKey.publicKey()
message = "This is the right message"
signature = EcdsaRuby::Ecdsa.sign(message, privateKey)
assertEqual(EcdsaRuby::Ecdsa.verify(message, signature, publicKey), true)

subHeader("testVerifyWrongMessage")
privateKey = EcdsaRuby::PrivateKey.new()
publicKey = privateKey.publicKey()
message1 = "This is the right message"
message2 = "This is the wrong message"
signature = EcdsaRuby::Ecdsa.sign(message1, privateKey)
assertEqual(EcdsaRuby::Ecdsa.verify(message2, signature, publicKey), false)


header("openSSL")

subHeader("testAssign")
# Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
privateKeyPem = EcdsaRuby::Utils::File.read("test/privateKey.pem")
privateKey = EcdsaRuby::PrivateKey.fromPem(privateKeyPem)
message = EcdsaRuby::Utils::File.read("test/message.txt")
signature = EcdsaRuby::Ecdsa.sign(message, privateKey)
publicKey = privateKey.publicKey()
assertEqual(EcdsaRuby::Ecdsa.verify(message, signature, publicKey), true)

subHeader("testVerifySignature")
# openssl ec -in privateKey.pem -pubout -out publicKey.pem
publicKeyPem = EcdsaRuby::Utils::File.read("test/publicKey.pem")
# openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
signatureDer = EcdsaRuby::Utils::File.read("test/signatureDer.txt", "binary")
message = EcdsaRuby::Utils::File.read("test/message.txt")
publicKey = EcdsaRuby::PublicKey.fromPem(publicKeyPem)
signature = EcdsaRuby::Signature.fromDer(signatureDer)
assertEqual(EcdsaRuby::Ecdsa.verify(message, signature, publicKey), true)


header("PrivateKey")

subHeader("testPemConversion")
privateKey1 = EcdsaRuby::PrivateKey.new()
pem = privateKey1.toPem()
privateKey2 = EcdsaRuby::PrivateKey.fromPem(pem)
assertEqual(privateKey1.secret, privateKey2.secret)
assertEqual(privateKey1.curve, privateKey2.curve)

subHeader("testDerConversion")
privateKey1 = EcdsaRuby::PrivateKey.new()
der = privateKey1.toDer()
privateKey2 = EcdsaRuby::PrivateKey.fromDer(der)
assertEqual(privateKey1.secret, privateKey2.secret)
assertEqual(privateKey1.curve, privateKey2.curve)

subHeader("testStringConversion")
privateKey1 = EcdsaRuby::PrivateKey.new()
string = privateKey1.toString()
privateKey2 = EcdsaRuby::PrivateKey.fromString(string)
assertEqual(privateKey1.secret, privateKey2.secret)
assertEqual(privateKey1.curve, privateKey2.curve)


header("PublicKey")

subHeader("testPemConversion")
privateKey = EcdsaRuby::PrivateKey.new()
publicKey1 = privateKey.publicKey()
pem = publicKey1.toPem()
publicKey2 = EcdsaRuby::PublicKey.fromPem(pem)
assertEqual(publicKey1.point.x, publicKey2.point.x)
assertEqual(publicKey1.point.y, publicKey2.point.y)
assertEqual(publicKey1.curve, publicKey2.curve)

subHeader("testDerConversion")
privateKey = EcdsaRuby::PrivateKey.new()
publicKey1 = privateKey.publicKey()
der = publicKey1.toDer()
publicKey2 = EcdsaRuby::PublicKey.fromDer(der)
assertEqual(publicKey1.point.x, publicKey2.point.x)
assertEqual(publicKey1.point.y, publicKey2.point.y)
assertEqual(publicKey1.curve, publicKey2.curve)


subHeader("testStringConversion")
privateKey = EcdsaRuby::PrivateKey.new()
publicKey1 = privateKey.publicKey()
string = publicKey1.toString()
publicKey2 = EcdsaRuby::PublicKey.fromString(string)
assertEqual(publicKey1.point.x, publicKey2.point.x)
assertEqual(publicKey1.point.y, publicKey2.point.y)
assertEqual(publicKey1.curve, publicKey2.curve)


header("Signature")

subHeader("testDerConversion")
privateKey = EcdsaRuby::PrivateKey.new()
message = "This is a text message"
signature1 = EcdsaRuby::Ecdsa.sign(message, privateKey)
der = signature1.toDer()
signature2 = EcdsaRuby::Signature.fromDer(der)
assertEqual(signature1.r, signature2.r)
assertEqual(signature1.s, signature2.s)

subHeader("testBase64Conversion")
privateKey = EcdsaRuby::PrivateKey.new()
message = "This is a text message"
signature1 = EcdsaRuby::Ecdsa.sign(message, privateKey)
base64 = signature1.toBase64()
signature2 = EcdsaRuby::Signature.fromBase64(base64)
assertEqual(signature1.r, signature2.r)
assertEqual(signature1.s, signature2.s)


puts "\n\nsuccess: #{success}"
puts "failure: #{failure}"